"""add server_protocols

Revision ID: 224cb2469685
Revises: 9030daae246f
Create Date: 2026-03-11 01:44:56.510462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224cb2469685'
down_revision = '9030daae246f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('protocol_type', sa.String(length=20), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('config_params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_protocols')
    # ### end Alembic commands ###
