"""Add cascade delete for traffic_stats

Revision ID: 30048d66db8c
Revises: 64220130af26
Create Date: 2026-03-23 21:22:19.872521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30048d66db8c'
down_revision = '64220130af26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_stats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('traffic_stats_client_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('traffic_stats_client_id_fkey'), 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###
