"""add groups

Revision ID: 33dec7f93b69
Revises: 599330cbf5f6
Create Date: 2026-03-14 00:08:58.606367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33dec7f93b69'
down_revision = '599330cbf5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('protocol_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('protocol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'server_groups', ['group_id'], ['id'])

    with op.batch_alter_table('haproxy_backends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'server_groups', ['group_id'], ['id'])

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'server_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('haproxy_backends', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('protocol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('protocol_type')
        batch_op.drop_column('group_id')

    op.drop_table('server_groups')
    # ### end Alembic commands ###
