"""add oidc endpoint urls

Revision ID: 64220130af26
Revises: e1a4a82f02c0
Create Date: 2026-03-23 16:20:40.121442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64220130af26'
down_revision = 'e1a4a82f02c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oidc_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorize_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('token_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('userinfo_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oidc_settings', schema=None) as batch_op:
        batch_op.drop_column('userinfo_url')
        batch_op.drop_column('token_url')
        batch_op.drop_column('authorize_url')

    # ### end Alembic commands ###
