"""add proxy

Revision ID: 801e8c5e56b7
Revises: c055dc905f07
Create Date: 2026-03-11 05:49:34.642043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801e8c5e56b7'
down_revision = 'c055dc905f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haproxy_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('ssh_username', sa.String(length=64), nullable=False),
    sa.Column('ssh_key_encrypted', sa.Text(), nullable=False),
    sa.Column('ssh_key_passphrase_encrypted', sa.Text(), nullable=True),
    sa.Column('config_path', sa.String(length=255), nullable=True),
    sa.Column('stats_socket_path', sa.String(length=255), nullable=True),
    sa.Column('stats_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('haproxy_backends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('protocol_type', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('balance_algorithm', sa.String(length=20), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('haproxy_server_id', sa.Integer(), nullable=False),
    sa.Column('servers_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['haproxy_server_id'], ['haproxy_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_stats_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_limit_check', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('last_limit_check')
        batch_op.drop_column('last_stats_update')

    op.drop_table('haproxy_backends')
    op.drop_table('haproxy_servers')
    # ### end Alembic commands ###
