"""add server model

Revision ID: 9030daae246f
Revises: 207cfd95cf8d
Create Date: 2026-03-11 01:32:28.344366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9030daae246f'
down_revision = '207cfd95cf8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_username', sa.String(length=64), nullable=False),
    sa.Column('ssh_key_encrypted', sa.Text(), nullable=True),
    sa.Column('ssh_key_passphrase_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    # ### end Alembic commands ###
