"""add clients table

Revision ID: c055dc905f07
Revises: 224cb2469685
Create Date: 2026-03-11 05:01:13.311024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c055dc905f07'
down_revision = '224cb2469685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('private_key_encrypted', sa.Text(), nullable=True),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.Column('traffic_limit_bytes', sa.BigInteger(), nullable=True),
    sa.Column('traffic_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['server_protocols.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
