"""add oidc

Revision ID: e1a4a82f02c0
Revises: 33dec7f93b69
Create Date: 2026-03-19 05:18:33.281578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a4a82f02c0'
down_revision = '33dec7f93b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub')
    )
    op.create_table('oidc_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_url', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('auto_group_id', sa.Integer(), nullable=True),
    sa.Column('auto_server_id', sa.Integer(), nullable=True),
    sa.Column('auto_protocol_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['auto_group_id'], ['server_groups.id'], ),
    sa.ForeignKeyConstraint(['auto_server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oidc_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'oidc_users', ['oidc_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('oidc_user_id')

    op.drop_table('oidc_settings')
    op.drop_table('oidc_users')
    # ### end Alembic commands ###
